name: Build and Publish Resume PDF

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/resume.pdf'  # Prevent infinite loop

permissions:
  contents: write

jobs:
  build-resume:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        working_directory: cv
        root_file: resume.tex
        compiler: pdflatex
        args: -interaction=nonstopmode -file-line-error

    - name: Move PDF to docs/ for GitHub Pages
      run: |
        mkdir -p docs
        mv cv/resume.pdf docs/resume.pdf

    - name: Commit and push updated resume.pdf
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add docs/resume.pdf
        git diff --cached --quiet || git commit -m "Update resume PDF"
        git push
