name: Build LaTeX Resume

on:
  push:
    branches: [ main, master ]
    paths:
      - 'cv/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'cv/**'
  workflow_dispatch:

jobs:
  build-resume:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        working_directory: cv
        root_file: resume.tex
        compiler: pdflatex
        args: -interaction=nonstopmode -file-line-error

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: resume-pdf
        path: cv/resume.pdf
        retention-days: 30

    - name: Copy PDF to repo root and commit
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        cp cv/resume.pdf ./resume.pdf
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add ./resume.pdf
        git commit -m "Update resume.pdf [skip ci]" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
