name: Build LaTeX Resume

on:
  push:
    branches: [ main, master ]
    paths:
      - 'cv/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'cv/**'
  workflow_dispatch: # Allow manual triggering

jobs:
  build-resume:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        working_directory: cv
        root_file: resume.tex
        compiler: pdflatex
        args: -interaction=nonstopmode -file-line-error
        
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: resume-pdf
        path: cv/resume.pdf
        retention-days: 30
        
    - name: Check if this is main/master branch
      id: check_branch
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" || "${{ github.ref }}" == "refs/heads/master" ]]; then
          echo "is_main=true" >> $GITHUB_OUTPUT
        else
          echo "is_main=false" >> $GITHUB_OUTPUT
        fi
        
    # Optional: Create a release with the PDF when pushing to main/master
    - name: Create Release
      if: steps.check_branch.outputs.is_main == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: resume-${{ github.run_number }}
        name: Resume Build ${{ github.run_number }}
        body: |
          Automatically generated resume PDF from commit ${{ github.sha }}
          
          Build date: ${{ github.event.head_commit.timestamp }}
        files: cv/resume.pdf
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
